In [1]:
import pandas as pd 
import numpy as np

import random

In [2]:
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split

In [3]:
%%time
dataset = pd.read_csv(r'data2\final_data.csv')



Wall time: 5.96 s


In [4]:
dataset

icmp  tcp  udp  IRC  X11  Z39_50  auth  bgp  courier  csnet_ns  ...  \
0        0.0  1.0  0.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   
1        0.0  0.0  1.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   
2        0.0  1.0  0.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   
3        0.0  1.0  0.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   
4        0.0  0.0  1.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   
...      ...  ...  ...  ...  ...     ...   ...  ...      ...       ...  ...   
139646   0.0  0.0  1.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   
139647   0.0  1.0  0.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   
139648   0.0  1.0  0.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   
139649   0.0  1.0  0.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   
139650   0.0  1.0  0.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   

        dst_host_srv_count  dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                 0.007843                    0.01                    0.06   
1                 0.972549                    0.97                    0.01   
2                 1.000000                    1.00                    0.00   
3                 0.054902                    0.05                    0.07   
4                 0.003922                    0.00                    0.85   
...                    ...                     ...                     ...   
139646            0.003922                    0.00                    0.69   
139647            1.000000                    1.00                    0.00   
139648            0.043137                    0.04                    0.07   
139649            1.000000                    1.00                    0.00   
139650            1.000000                    1.00                    0.00   

        dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                              0.00                         0.00   
1                              0.01                         0.00   
2                              0.01                         0.02   
3                              0.00                         0.00   
4                              1.00                         0.00   
...                             ...                          ...   
139646                         0.98                         0.00   
139647                         0.02                         0.02   
139648                         0.00                         0.00   
139649                         0.00                         0.01   
139650                         1.00                         0.03   

        dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                        1.0                       1.0                   0.0   
1                        0.0                       0.0                   0.0   
2                        0.0                       0.0                   0.0   
3                        0.0                       0.0                   1.0   
4                        0.0                       0.0                   0.0   
...                      ...                       ...                   ...   
139646                   0.0                       0.0                   0.0   
139647                   0.0                       0.0                   0.0   
139648                   1.0                       1.0                   0.0   
139649                   0.0                       0.0                   0.0   
139650                   0.0                       0.0                   0.0   

        dst_host_srv_rerror_rate     label  
0                            0.0  0.187269  
1                            0.0  0.714664  
2                            0.0  0.934109  
3                            1.0  0.475358  
4                            0.0  0.633880  
...                          ...       ...  
139646                       

### Split data

In [5]:
X, y = dataset.drop(columns='label'), dataset[['label']]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [7]:
X_train

icmp  tcp  udp  IRC  X11  Z39_50  auth  bgp  courier  csnet_ns  ...  \
116727   0.0  1.0  0.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   
107737   0.0  1.0  0.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   
14522    0.0  1.0  0.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   
45931    0.0  1.0  0.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   
114911   0.0  1.0  0.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   
...      ...  ...  ...  ...  ...     ...   ...  ...      ...       ...  ...   
110268   0.0  1.0  0.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   
119879   0.0  1.0  0.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   
103694   0.0  1.0  0.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   
131932   0.0  1.0  0.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   
121958   0.0  1.0  0.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   

        dst_host_count  dst_host_srv_count  dst_host_same_srv_rate  \
116727        0.545098            1.000000                    1.00   
107737        1.000000            0.070588                    0.07   
14522         0.792157            0.666667                    0.64   
45931         0.274510            1.000000                    1.00   
114911        1.000000            0.054902                    0.05   
...                ...                 ...                     ...   
110268        0.407843            0.792157                    0.95   
119879        0.039216            1.000000                    1.00   
103694        0.921569            1.000000                    1.00   
131932        0.137255            0.600000                    0.83   
121958        1.000000            1.000000                    1.00   

        dst_host_diff_srv_rate  dst_host_same_src_port_rate  \
116727                    0.00                         0.01   
107737                    0.06                         0.00   
14522                     0.03                         0.00   
45931                     0.00                         0.01   
114911                    0.07                         0.00   
...                        ...                          ...   
110268                    0.02                         0.01   
119879                    0.00                         0.10   
103694                    0.00                         0.00   
131932                    0.09                         0.03   
121958                    0.00                         0.00   

        dst_host_srv_diff_host_rate  dst_host_serror_rate  \
116727                         0.03                  0.01   
107737                         0.00                  1.00   
14522                          0.01                  0.00   
45931                          0.04                  0.00   
114911                         0.00                  1.00   
...                             ...                   ...   
110268                         0.01                  0.00   
119879                         0.02                  0.00   
103694                         0.01                  0.00   
131932                         0.01                  0.00   
121958                         0.00                  0.00   

        dst_host_srv_serror_rate  dst_host_rerror_rate  \
116727                      0.00                   0.0   
107737                      1.00                   0.0   
14522                       0.01                   0.0   
45931                       0.00                   0.0   
114911                      1.00                   0.0   
...                          ...                   ...   
110268                      0.00                   0.0   
119879                      0.00                   0.0   
103694                      0.00                   0.0   
131932                      0.01                   0.0   
121958                      0.00                   0.0   

        dst_host_srv_rerror_rat

In [15]:
X_test

icmp  tcp  udp  IRC  X11  Z39_50  auth  bgp  courier  csnet_ns  ...  \
133793   0.0  1.0  0.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   
38956    0.0  1.0  0.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   
138452   0.0  1.0  0.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   
48327    0.0  1.0  0.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   
110851   0.0  1.0  0.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   
...      ...  ...  ...  ...  ...     ...   ...  ...      ...       ...  ...   
128272   0.0  1.0  0.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   
114289   0.0  1.0  0.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   
77448    0.0  1.0  0.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   
24098    0.0  1.0  0.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   
31214    0.0  1.0  0.0  0.0  0.0     0.0   0.0  0.0      0.0       0.0  ...   

        dst_host_count  dst_host_srv_count  dst_host_same_srv_rate  \
133793        0.274510            1.000000                    1.00   
38956         0.180392            0.200000                    0.41   
138452        1.000000            0.019608                    0.02   
48327         0.298039            0.137255                    0.46   
110851        1.000000            0.027451                    0.03   
...                ...                 ...                     ...   
128272        0.129412            1.000000                    1.00   
114289        0.070588            0.827451                    0.94   
77448         1.000000            1.000000                    1.00   
24098         1.000000            1.000000                    1.00   
31214         0.011765            1.000000                    1.00   

        dst_host_diff_srv_rate  dst_host_same_src_port_rate  \
133793                    0.00                         0.01   
38956                     0.11                         0.41   
138452                    0.07                         0.00   
48327                     0.04                         0.46   
110851                    0.06                         0.00   
...                        ...                          ...   
128272                    0.00                         0.03   
114289                    0.11                         0.06   
77448                     0.00                         0.00   
24098                     0.00                         0.00   
31214                     0.00                         0.33   

        dst_host_srv_diff_host_rate  dst_host_serror_rate  \
133793                         0.02                   0.0   
38956                          0.04                   0.0   
138452                         0.00                   1.0   
48327                          0.00                   0.0   
110851                         0.00                   1.0   
...                             ...                   ...   
128272                         0.02                   0.0   
114289                         0.01                   0.0   
77448                          0.00                   0.0   
24098                          0.00                   0.0   
31214                          0.04                   0.0   

        dst_host_srv_serror_rate  dst_host_rerror_rate  \
133793                       0.0                   0.0   
38956                        0.0                   0.0   
138452                       1.0                   0.0   
48327                        0.0                   0.0   
110851                       1.0                   0.0   
...                          ...                   ...   
128272                       0.0                   0.0   
114289                       0.0                   0.0   
77448                        0.0                   0.0   
24098                        0.0                   0.0   
31214                        0.0                   0.0   

        dst_host_srv_rerror_rat

In [8]:
def logfunc(x):
    return 1.0/(1 + np.exp(-x))

In [9]:
epoch_count = 1

epsilon = 0.01

I_dim = 115
H_dim = 10

weights_ItoH = np.random.uniform(-1, 1, (I_dim, H_dim))
weights_HtoO = np.random.uniform(-1, 1, H_dim)

preActivation_H = np.zeros(H_dim)
postActivation_H = np.zeros(H_dim)

In [ ]:
# learning


def learn_perceptron():
    global weights_ItoH, weights_HtoO, preActivation_H, postActivation_H
    #global weights_HtoO
    
    for epoch in range(epoch_count):
        for sample in range(len(X_train.iloc[:, 0])):
            if ((sample+1) %500) == 0:
                print('Current sample:',  sample+1)  
            for node in range(H_dim):
                preActivation_H[node] = np.dot(X_train.iloc[sample], weights_ItoH[:, node])
                postActivation_H[node] = logfunc(preActivation_H[node])

            preActivation_O = np.dot(postActivation_H, weights_HtoO)
            postActivation_O = logfunc(preActivation_O)

            Y_real = y_train.iloc[sample][0]

            dn = abs((Y_real - postActivation_O)/Y_real)

            if dn < epsilon:
                pass

            else:
                q3 = postActivation_O*(1 - postActivation_O)* (Y_real - postActivation_O)
                for node in range(H_dim):
                    q2 = postActivation_H[node]* (1 - postActivation_H[node])* (q3 * weights_HtoO[node])
                    weights_ItoH[:, node] = weights_ItoH[:, node] + q2 * X_train.iloc[sample]

                weights_HtoO = postActivation_H * q3 + weights_HtoO

    #return weights_ItoH, weights_HtoO
            

In [ ]:
%%time
learn_perceptron()

In [13]:
#recognizing

y_test_arr = y_test.to_numpy()
recog_arr = np.zeros(len(y_test))

def recognizing():
    global weights_ItoH, weights_HtoO, preActivation_H, postActivation_H, \
        y_test_arr, recog_arr
    
    for sample in range(len(X_test.iloc[:, 0])):
        if ((sample+1) %500) == 0:
                print('Current sample:',  sample+1)  
        for node in range(H_dim):
                preActivation_H[node] = np.dot(X_test.iloc[sample], weights_ItoH[:, node])
                postActivation_H[node] = logfunc(preActivation_H[node])

        preActivation_O = np.dot(postActivation_H, weights_HtoO)
        postActivation_O = logfunc(preActivation_O)

        recog_arr[sample] = postActivation_O
    

In [14]:
%%time
recognizing()

Current sample: 500
Current sample: 1000
Current sample: 1500
Current sample: 2000
Current sample: 2500
Current sample: 3000
Current sample: 3500
Current sample: 4000
Current sample: 4500
Current sample: 5000
Current sample: 5500
Current sample: 6000
Current sample: 6500
Current sample: 7000
Current sample: 7500
Current sample: 8000
Current sample: 8500
Current sample: 9000
Current sample: 9500
Current sample: 10000
Current sample: 10500
Current sample: 11000
Current sample: 11500
Current sample: 12000
Current sample: 12500
Current sample: 13000
Current sample: 13500
Current sample: 14000
Current sample: 14500
Current sample: 15000
Current sample: 15500
Current sample: 16000
Current sample: 16500
Current sample: 17000
Current sample: 17500
Current sample: 18000
Current sample: 18500
Current sample: 19000
Current sample: 19500
Current sample: 20000
Current sample: 20500
Current sample: 21000
Current sample: 21500
Current sample: 22000
Current sample: 22500
Current sample: 23000
Current 

In [16]:
y_test_arr

array([[0.89074813],
       [0.64036892],
       [0.49088763],
       ...,
       [0.69580145],
       [0.55496934],
       [0.86654916]])

In [18]:
recog_arr

array([0.76438015, 0.76639085, 0.24935674, ..., 0.76141038, 0.76091842,
       0.76453172])

In [19]:
# round

y_test_arr_r = np.around(y_test_arr).reshape(-1)
recog_arr_r = np.around(recog_arr)

In [20]:
y_test_arr_r

array([1., 1., 0., ..., 1., 1., 1.])

In [21]:
recog_arr_r

array([1., 1., 0., ..., 1., 1., 1.])

In [22]:
# metrics
 

from sklearn.metrics import confusion_matrix, classification_report

tn, fp, fn, tp = confusion_matrix(y_test_arr_r, recog_arr_r).ravel()
print('tn = {}, fp = {}, fn = {}, tp = {}'.format(str(tn), str(fp), str(fn), str(tp)))

print('---------------------------\n')

target_names = ['neptune', 'normal']
print(classification_report(y_test_arr_r, recog_arr_r, target_names=target_names))



tn = 15486, fp = 2, fn = 6, tp = 26402
---------------------------

              precision    recall  f1-score   support

     neptune       1.00      1.00      1.00     15488
      normal       1.00      1.00      1.00     26408

    accuracy                           1.00     41896
   macro avg       1.00      1.00      1.00     41896
weighted avg       1.00      1.00      1.00     41896



In [23]:
np.histogram(y_test_arr_r, bins=2)

(array([15488, 26408], dtype=int64), array([0. , 0.5, 1. ]))

In [24]:
np.histogram(recog_arr_r, bins=2)

(array([15492, 26404], dtype=int64), array([0. , 0.5, 1. ]))

In [ ]:
#np.savez('weights_arr', weights_ItoH=weights_ItoH, weights_HtoO=weights_HtoO)

In [10]:
load_arr = np.load('weights_arr.npz')

In [11]:
load_arr.files

['weights_ItoH', 'weights_HtoO']

In [12]:
weights_ItoH, weights_HtoO = load_arr['weights_ItoH'], load_arr['weights_HtoO']