In [3]:
import pandas as pd 
import numpy as np

import random

In [4]:
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split

In [5]:
%%time
dataset = pd.read_csv(r'label_final_data.csv')



Wall time: 1.03 s


In [6]:
dataset

duration  protocol_type   service  flag  src_bytes  dst_bytes  land  \
0       0.000000            0.5  0.687500   0.5   0.000000   0.000000   0.0   
1       0.000000            0.5  0.687500   0.5   0.000000   0.000000   0.0   
2       0.000017            0.5  0.765625   1.0   0.000645   0.000073   0.0   
3       0.000000            0.5  0.687500   0.5   0.000000   0.000000   0.0   
4       0.000000            0.5  0.343750   1.0   0.000139   0.001988   0.0   
...          ...            ...       ...   ...        ...        ...   ...   
139646  0.000000            0.5  0.687500   0.5   0.000000   0.000000   0.0   
139647  0.000000            0.5  0.687500   0.5   0.000000   0.000000   0.0   
139648  0.000000            0.5  0.343750   1.0   0.000100   0.000625   0.0   
139649  0.000000            0.5  0.687500   0.5   0.000000   0.000000   0.0   
139650  0.000000            0.5  0.687500   0.5   0.000000   0.000000   0.0   

        wrong_fragment  urgent  hot  ...  dst_host_srv_count  \
0                  0.0     0.0  0.0  ...            0.078431   
1                  0.0     0.0  0.0  ...            0.043137   
2                  0.0     0.0  0.0  ...            0.933333   
3                  0.0     0.0  0.0  ...            0.090196   
4                  0.0     0.0  0.0  ...            1.000000   
...                ...     ...  ...  ...                 ...   
139646             0.0     0.0  0.0  ...            0.027451   
139647             0.0     0.0  0.0  ...            0.003922   
139648             0.0     0.0  0.0  ...            1.000000   
139649             0.0     0.0  0.0  ...            0.027451   
139650             0.0     0.0  0.0  ...            0.078431   

        dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                         0.08                    0.07   
1                         0.04                    0.06   
2                         0.95                    0.02   
3                         0.09                    0.06   
4                         1.00                    0.00   
...                        ...                     ...   
139646                    0.03                    0.10   
139647                    0.00                    0.08   
139648                    1.00                    0.00   
139649                    0.03                    0.07   
139650                    0.08                    0.08   

        dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                              0.00                         0.00   
1                              0.00                         0.00   
2                              0.01                         0.01   
3                              0.00                         0.00   
4                              0.33                         0.02   
...                             ...                          ...   
139646                         0.00                         0.00   
139647                         0.00                         0.00   
139648                         0.25                         0.02   
139649                         0.00                         0.00   
139650                         0.00                         0.00   

        dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                        1.0                       1.0                   0.0   
1                        1.0                       1.0                   0.0   
2                        0.0                       0.0                   0.0   
3                        1.0                       1.0                   0.0   
4                        0.0                       0.0                   0.0   
...                      ...                       ...                   ...   
139646                   1.0                       1.0                   0.0   
139647                   1.0                       1.0                   0.0   
139648                   0.0                       0.0  

In [7]:
df= pd.concat([dataset[dataset['label'] >= 0.5][:100], dataset[dataset['label'] < 0.5][:200]])
df =df.sample(frac=1, random_state=42).reset_index(drop=True) 
df

duration  protocol_type   service   flag  src_bytes  dst_bytes  land  \
0         0.0            0.5  0.687500  0.500   0.000000   0.000000   0.0   
1         0.0            0.5  0.390625  0.125   0.000000   0.000000   0.0   
2         0.0            0.5  0.687500  0.500   0.000000   0.000000   0.0   
3         0.0            0.5  0.343750  1.000   0.000134   0.000049   0.0   
4         0.0            0.5  0.687500  0.500   0.000000   0.000000   0.0   
..        ...            ...       ...    ...        ...        ...   ...   
295       0.0            0.5  0.687500  0.500   0.000000   0.000000   0.0   
296       0.0            0.5  0.343750  1.000   0.000154   0.000076   0.0   
297       0.0            0.5  0.687500  0.500   0.000000   0.000000   0.0   
298       0.0            0.5  0.687500  0.500   0.000000   0.000000   0.0   
299       0.0            0.5  0.687500  0.500   0.000000   0.000000   0.0   

     wrong_fragment  urgent  hot  ...  dst_host_srv_count  \
0               0.0     0.0  0.0  ...            0.070588   
1               0.0     0.0  0.0  ...            0.003922   
2               0.0     0.0  0.0  ...            0.098039   
3               0.0     0.0  0.0  ...            1.000000   
4               0.0     0.0  0.0  ...            0.058824   
..              ...     ...  ...  ...                 ...   
295             0.0     0.0  0.0  ...            0.074510   
296             0.0     0.0  0.0  ...            1.000000   
297             0.0     0.0  0.0  ...            0.062745   
298             0.0     0.0  0.0  ...            0.011765   
299             0.0     0.0  0.0  ...            0.090196   

     dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                      0.07                    0.07   
1                      0.00                    0.07   
2                      0.10                    0.05   
3                      1.00                    0.00   
4                      0.06                    0.08   
..                      ...                     ...   
295                    0.07                    0.07   
296                    1.00                    0.00   
297                    0.06                    0.05   
298                    0.01                    0.07   
299                    0.09                    0.06   

     dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                            0.0                          0.0   
1                            0.0                          0.0   
2                            0.0                          0.0   
3                            0.0                          0.0   
4                            0.0                          0.0   
..                           ...                          ...   
295                          0.0                          0.0   
296                          0.0                          0.0   
297                          0.0                          0.0   
298                          0.0                          0.0   
299                          0.0                          0.0   

     dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                     1.0                       1.0                   0.0   
1                     0.0                       0.0                   1.0   
2                     1.0                       1.0                   0.0   
3                     0.0                       0.0                   0.0   
4                     1.0                       1.0                   0.0   
..                    ...                       ...                   ...   
295                   1.0                       1.0                   0.0   
296                   0.0                       0.0                   0.0   
297                   1.0                       1.0                   0.0   
298                   1.0                       1.0                   0.0   
299                   1.0                       1.0       

### Split data

In [24]:
X, y = df.drop(columns='label'), df[['label']]

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [33]:
X_train

duration  protocol_type   service   flag  src_bytes  dst_bytes  land  \
194  0.000000            0.5  0.687500  0.500   0.000000   0.000000   0.0   
101  0.044918            1.0  0.625000  1.000   0.000067   0.000020   0.0   
68   0.000000            1.0  0.687500  1.000   0.000048   0.000000   0.0   
224  0.000000            1.0  0.171875  1.000   0.000015   0.000000   0.0   
37   0.000000            1.0  0.171875  1.000   0.000016   0.000000   0.0   
..        ...            ...       ...    ...        ...        ...   ...   
188  0.000000            0.5  0.765625  1.000   0.000371   0.000065   0.0   
71   0.000000            0.5  0.687500  0.125   0.000000   0.000000   0.0   
106  0.000000            0.5  0.687500  0.500   0.000000   0.000000   0.0   
270  0.000000            0.5  0.296875  1.000   0.002702   0.000000   0.0   
102  0.000000            0.5  0.343750  1.000   0.000121   0.000136   0.0   

     wrong_fragment  urgent  hot  ...  dst_host_count  dst_host_srv_count  \
194             0.0     0.0  0.0  ...        1.000000            0.058824   
101             0.0     0.0  0.0  ...        1.000000            0.007843   
68              0.0     0.0  0.0  ...        1.000000            0.945098   
224             0.0     0.0  0.0  ...        0.658824            0.105882   
37              0.0     0.0  0.0  ...        0.282353            0.133333   
..              ...     ...  ...  ...             ...                 ...   
188             0.0     0.0  0.0  ...        0.035294            0.639216   
71              0.0     0.0  0.0  ...        1.000000            0.023529   
106             0.0     0.0  0.0  ...        1.000000            0.078431   
270             0.0     0.0  0.0  ...        0.313725            0.062745   
102             0.0     0.0  0.0  ...        0.356863            1.000000   

     dst_host_same_srv_rate  dst_host_diff_srv_rate  \
194                    0.06                    0.06   
101                    0.01                    0.87   
68                     0.95                    0.01   
224                    0.16                    0.04   
37                     0.08                    0.08   
..                      ...                     ...   
188                    0.22                    0.33   
71                     0.02                    0.06   
106                    0.08                    0.06   
270                    0.15                    0.06   
102                    1.00                    0.00   

     dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
194                         0.00                         0.00   
101                         1.00                         0.00   
68                          0.00                         0.00   
224                         0.16                         0.00   
37                          0.08                         0.06   
..                           ...                          ...   
188                         0.11                         0.02   
71                          0.00                         0.00   
106                         0.00                         0.00   
270                         0.15                         0.12   
102                         0.01                         0.02   

     dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
194                  1.00                       1.0                   0.0   
101                  0.00                       0.0                   0.0   
68                   0.00                       0.0                   0.0   
224                  0.01                       0.0                   0.0   
37                   0.00                       0.0                   0.0   
..                    ...                       ...                   ...   
188                  0.00                       0.0                   0.0   
71                   0.00                       0.0                   1.0   
106                 

In [34]:
X_test

duration  protocol_type  service   flag  src_bytes  dst_bytes  land  \
203       0.0            0.5   0.6875  0.500        0.0        0.0   0.0   
266       0.0            0.5   0.6875  0.500        0.0        0.0   0.0   
152       0.0            0.5   0.6875  0.125        0.0        0.0   0.0   
9         0.0            0.5   0.6875  0.500        0.0        0.0   0.0   
233       0.0            0.5   0.6875  0.125        0.0        0.0   0.0   
..        ...            ...      ...    ...        ...        ...   ...   
114       0.0            0.5   0.6875  0.500        0.0        0.0   0.0   
118       0.0            0.5   0.6875  0.125        0.0        0.0   0.0   
72        0.0            0.5   0.6875  0.125        0.0        0.0   0.0   
15        0.0            0.5   0.6875  0.500        0.0        0.0   0.0   
10        0.0            0.5   0.6875  0.500        0.0        0.0   0.0   

     wrong_fragment  urgent  hot  ...  dst_host_count  dst_host_srv_count  \
203             0.0     0.0  0.0  ...             1.0            0.074510   
266             0.0     0.0  0.0  ...             1.0            0.058824   
152             0.0     0.0  0.0  ...             1.0            0.070588   
9               0.0     0.0  0.0  ...             1.0            0.086275   
233             0.0     0.0  0.0  ...             1.0            0.019608   
..              ...     ...  ...  ...             ...                 ...   
114             0.0     0.0  0.0  ...             1.0            0.023529   
118             0.0     0.0  0.0  ...             1.0            0.050980   
72              0.0     0.0  0.0  ...             1.0            0.047059   
15              0.0     0.0  0.0  ...             1.0            0.054902   
10              0.0     0.0  0.0  ...             1.0            0.058824   

     dst_host_same_srv_rate  dst_host_diff_srv_rate  \
203                    0.07                    0.08   
266                    0.06                    0.06   
152                    0.07                    0.08   
9                      0.09                    0.05   
233                    0.02                    0.07   
..                      ...                     ...   
114                    0.02                    0.08   
118                    0.05                    0.07   
72                     0.05                    0.07   
15                     0.05                    0.07   
10                     0.06                    0.07   

     dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
203                          0.0                          0.0   
266                          0.0                          0.0   
152                          0.0                          0.0   
9                            0.0                          0.0   
233                          0.0                          0.0   
..                           ...                          ...   
114                          0.0                          0.0   
118                          0.0                          0.0   
72                           0.0                          0.0   
15                           0.0                          0.0   
10                           0.0                          0.0   

     dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
203                   1.0                       1.0                   0.0   
266                   1.0                       1.0                   0.0   
152                   0.0                       0.0                   1.0   
9                     1.0                       1.0                   0.0   
233                   0.0                       0.0                   1.0   
..                    ...                       ...                   ...   
114                   1.0                       1.0                   0.0   
118                   0.0                       0.0                   1.0   
72                    0.0       

In [35]:
def logfunc(x):
    return 1.0/(1 + np.exp(-x))

In [36]:
epoch_count = 100

epsilon = 0.01

I_dim = 41
H_dim = 3

weights_ItoH = np.random.uniform(-1, 1, (I_dim, H_dim))
weights_HtoO = np.random.uniform(-1, 1, H_dim)

preActivation_H = np.zeros(H_dim)
postActivation_H = np.zeros(H_dim)

In [37]:
# learning


def learn_perceptron():
    global weights_ItoH, weights_HtoO, preActivation_H, postActivation_H
    #global weights_HtoO
    
    for epoch in range(epoch_count):
        
        err = 0
        for sample in range(len(X_train.iloc[:, 0])):
            if ((sample+1) %500) == 0:
                print('Current sample:',  sample+1)  
            for node in range(H_dim):
                preActivation_H[node] = np.dot(X_train.iloc[sample], weights_ItoH[:, node])
                postActivation_H[node] = logfunc(preActivation_H[node])

            preActivation_O = np.dot(postActivation_H, weights_HtoO)
            postActivation_O = logfunc(preActivation_O)

            Y_real = y_train.iloc[sample][0]

            dn = abs((Y_real - postActivation_O)/Y_real)
            
            #print(dn)

            if dn < epsilon:
                pass

            else:
                q3 = postActivation_O*(1 - postActivation_O)* (Y_real - postActivation_O)
                for node in range(H_dim):
                    q2 = postActivation_H[node]* (1 - postActivation_H[node])* (q3 * weights_HtoO[node])
                    weights_ItoH[:, node] = weights_ItoH[:, node] + q2 * X_train.iloc[sample]

                weights_HtoO = postActivation_H * q3 + weights_HtoO
                
            err += dn
            
        net_error = err/(len(X_train.iloc[:, 0])+1)
        
        if epoch in [0, 49, 99]  :
            print('-------{} epocha-------'.format(epoch+1))
            print('Net error:', net_error, '\n')

    #return weights_ItoH, weights_HtoO
            

In [38]:
%%time
learn_perceptron()

-------1 epocha-------
Net error: 2.6154091434501576 

-------50 epocha-------
Net error: 1.7339775706568188 

-------100 epocha-------
Net error: 1.6954725629683527 

Wall time: 47.8 s


In [16]:
#recognizing

y_test_arr = y_test.to_numpy()
recog_arr = np.zeros(len(y_test))

def recognizing():
    global weights_ItoH, weights_HtoO, preActivation_H, postActivation_H, \
        y_test_arr, recog_arr
    
    for sample in range(len(X_test.iloc[:, 0])):
        if ((sample+1) %500) == 0:
                print('Current sample:',  sample+1)  
        for node in range(H_dim):
                preActivation_H[node] = np.dot(X_test.iloc[sample], weights_ItoH[:, node])
                postActivation_H[node] = logfunc(preActivation_H[node])

        preActivation_O = np.dot(postActivation_H, weights_HtoO)
        postActivation_O = logfunc(preActivation_O)

        recog_arr[sample] = postActivation_O
    

In [17]:
%%time
recognizing()

Wall time: 114 ms


In [ ]:
y_test_arr

In [327]:
recog_arr

array([0.23866195, 0.27540386, 0.23424607, 0.24039679, 0.22043637,
       0.26493036, 0.24664762, 0.71914984, 0.24367519, 0.23958468,
       0.72032351, 0.84622299, 0.22682537, 0.71860372, 0.19248487,
       0.23892627, 0.71456169, 0.23440548, 0.71356078, 0.23788481,
       0.85403168, 0.234716  , 0.69768549, 0.19395381, 0.19469568,
       0.28224774, 0.71504461, 0.24894016, 0.7271197 , 0.28714535,
       0.19492291, 0.76984432, 0.714239  , 0.26468903, 0.75916609,
       0.25228256, 0.20311789, 0.23134655, 0.26136021, 0.26018148,
       0.22209707, 0.78892419, 0.44707198, 0.23638214, 0.78929773,
       0.23995295, 0.25060954, 0.26259823, 0.28064393, 0.23106167,
       0.28361742, 0.24474055, 0.24112448, 0.19761449, 0.27855587,
       0.7506208 , 0.24319586, 0.71275237, 0.26931645, 0.76109654,
       0.21983969, 0.76903986, 0.29465943, 0.25146641, 0.76411424,
       0.71029684, 0.44568291, 0.78088492, 0.74445877, 0.24202234,
       0.23834759, 0.71136899, 0.79483874, 0.19951506, 0.20038

In [18]:
# round

y_test_arr_r = np.around(y_test_arr).reshape(-1)
recog_arr_r = np.around(recog_arr)

In [19]:
y_test_arr_r

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0.,
       1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1.,
       1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.])

In [20]:
recog_arr_r

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0.,
       1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1.,
       1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.])

In [21]:
# metrics
 

from sklearn.metrics import confusion_matrix, classification_report

tn, fp, fn, tp = confusion_matrix(y_test_arr_r, recog_arr_r).ravel()
print('tn = {}, fp = {}, fn = {}, tp = {}'.format(str(tn), str(fp), str(fn), str(tp)))

print('---------------------------\n')

target_names = ['neptune', 'normal']
print(classification_report(y_test_arr_r, recog_arr_r, target_names=target_names))



tn = 61, fp = 0, fn = 0, tp = 29
---------------------------

              precision    recall  f1-score   support

     neptune       1.00      1.00      1.00        61
      normal       1.00      1.00      1.00        29

    accuracy                           1.00        90
   macro avg       1.00      1.00      1.00        90
weighted avg       1.00      1.00      1.00        90



In [22]:
np.histogram(y_test_arr_r, bins=2)

(array([61, 29], dtype=int64), array([0. , 0.5, 1. ]))

In [23]:
np.histogram(recog_arr_r, bins=2)

(array([61, 29], dtype=int64), array([0. , 0.5, 1. ]))

In [ ]:
#np.savez('weights_arr', weights_ItoH=weights_ItoH, weights_HtoO=weights_HtoO)

In [10]:
load_arr = np.load('weights_arr.npz')

In [11]:
load_arr.files

['weights_ItoH', 'weights_HtoO']

In [12]:
weights_ItoH, weights_HtoO = load_arr['weights_ItoH'], load_arr['weights_HtoO']